name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t examen-backend:${{ github.sha }} .
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push Docker image
      run: |
        docker tag examen-backend:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/examen-backend:${{ github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/examen-backend:${{ github.sha }}
